docs/guides.md
Just fixed a small typo I ran over in guides.md.
=> Tiny typo fix in guides.md

guide/2-Language/switch.md, src/util/markdown.imba
This resolves the following build issue
```
TypeError: Cannot read property 'toString' of undefined
at Renderer.renderer.code (/Users/ccscanf/src/github.com/imba/imba.io.git/src/util/markdown.imba:219:22)
at Parser.tok (/Users/ccscanf/src/github.com/imba/imba.io.git/node_modules/marked/lib/marked.js:999:28)
at Parser.parse (/Users/ccscanf/src/github.com/imba/imba.io.git/node_modules/marked/lib/marked.js:944:17)
at Object.exports.render.self.render (/Users/ccscanf/src/github.com/imba/imba.io.git/src/util/markdown.imba:298:23)
at add (/Users/ccscanf/src/github.com/imba/imba.io.git/src/data/guide.imba:33:18)
at add (/Users/ccscanf/src/github.com/imba/imba.io.git/src/data/guide.imba:27:5)
at new Guide (/Users/ccscanf/src/github.com/imba/imba.io.git/src/data/guide.imba:63:2)
at …
```
=> fix consistency issue in the switch statement example

guide/1-Essentials/introduction.md, guide/3-Miscellaneous/Tooling/tools.md
This is related to trimming down the imba readme file in https://github.com/imba/imba/pull/219
=> reuse the descriptions from the imba project readme file

src/views/Site.imba
Added link to twitter account on navigation bar
https://github.com/imba/imba.io/issues/69
=> Added link to twitter account on navbar

.dockerignore, Dockerfile, package.json
This will make it super easy to deploy the website and reduce setup time
for someone who already has Docker installed.
=> Add docker support

tr-TR/guide/2-Language/basics.md, tr-TR/guide/hero.md, tr-TR/guide/scrimba.md, tr-TR/guide/welcome.md
I've translated hero.md, scrimba.md, welcome.md and basics.md files.
=> Turkish translation added.

guide/2-Language/loops.md
Added Range for-in loop doc.
closes #47 .
=> Added doc for range looping in imba

package.json, src/data/guide.imba
This uses write-good[0] for the English linting and the render doc is
also triggered so we can see the compilation errors.
[0]: https://github.com/btford/write-good/
=> setup a script for linting the guide

guide/community.md
fixed YouTube link
Youtube link was not working, was missing `https://`
=> Update community.md fixed YouTube link

content/intro.md
=> fixed "open opens" typo

content/intro.md, content/manual.md
konw -> know
imba (in text) -> Imba
Letter case use for "Imba" was inconsistent in the docs. Changed them to uppercase. 
(only in the text form explanation parts, I left it as imba in code parts)
=> Typo and letter case fixes

content/intro.md, content/language.md, content/tags.md, src/components/app-document.imba, src/components/app-menu.imba
I started going through the docs, so far I've made small style tweaks, some language/grammar tweaks and added several examples. I'll continue filling out empty areas of the docs next. This isn't ready but I wanted to get this up sooner so people can see it and tell me if I'm doing anything wrong.
=> Initial improvements to docs

content/language.md, content/styling.md, content/tags.md, src/components/app-document.imba, src/components/doc-widgets.imba
Added several examples, expanded some sections, filled in [wip] tag where appropriate and other small changes.
=> Trafnar v2 friday improvements

README.md, content/intro.md, content/language.md, package.json, src/components/app-menu.imba, src/index.imba, webpack.config.js
This should be enough so that the front page of the documentation can serve as a landing page and replace the v1 website for now until we have a proper home page.
=> Update front page of documentation to serve as landing page (Fixes #167)

content/language.md, content/styling.md, content/tags.md
Adding missing sections in Language from #163
=> Expanding docs

content/events.md
Adding some simple description to the denounce event modifier docs
=> Andre update event docs

README.md
=> Updated to show correct watch script

content/language.md
Adding a `Getting Started` section to the homepage docs. This can later be improved to mention upcoming base templates
=> Adding docs quickstart section

content/examples/90-7guis/04-timer/app.imba, content/examples/90-7guis/04-timer/index.html, content/examples/90-7guis/05-crud/app.imba, content/examples/90-7guis/05-crud/index.html, content/examples/90-7guis/06-circle-drawer/app.imba, content/examples/90-7guis/06-circle-drawer/index.html
These can be checked/improved upon but should work well enough for now. Circle drawer needs undo/redo functionality adding
=> Adding timer/crud/circle gui examples

content/tags.md
Fix typo in tags.md
"tough" -> "though"
N/A
=> Fix typo in tags.md

content/css.md, content/events.md, content/examples/90-7guis/01-counter/app.imba, content/examples/90-7guis/02-temperature/app.imba, content/examples/css/bottom.imba, content/examples/css/height.imba, content/examples/css/left.imba, content/examples/css/margin-bottom.imba, content/examples/css/margin-left.imba, content/examples/css/margin-right.imba, content/examples/css/margin-top.imba, content/examples/css/mx.imba, content/examples/css/my.imba, content/examples/css/padding-bottom.imba, content/examples/css/padding-left.imba, content/examples/css/padding-right.imba, content/examples/css/padding-top.imba, content/examples/css/positioning.imba, content/examples/css/py.imba, content/examples/css/right.imba, content/examples/css/size.imba, content/examples/css/top.imba, content/examples/css/width.imba, content/examples/util/styles.imba, content/language.md, src/components/app-document.imba
=> General doc changes + more text on event modifier pages

content/language.md
=> Correct spelling of idiomatic from "ideomatic"

content/events.md, content/language.md, content/tags.md
Adds examples for some of the "wip" sections such as state management, selection event and mouse event
In my browser locally
=> Add examples for state management, selection event and mouse event

content/tags.md
adds documentation and examples for `<global>`
=> document the global tag

content/language.md
```
npm run build && npm start
```
=> make operator docs for ?= clearer

content/docs/declarative-rendering.md, content/docs/grammar.md, content/docs/routing.md, content/docs/tags.md, content/docs/variables.md, old-content/manual.md, old-content/tags.md
Simple typo fixes reported by @YinChuRijnaard.
=> fix typos with @YinChuRijnaard

content/guides/deployment.md, content/guides/run-in-production.md
- Node v18 for full stack Imba: https://github.com/imba/imba-base-template
- Node v16 for static site hosting: https://github.com/imba/imba-vite-template
=> Update guides with Node version recommendations

content/docs/basic-syntax.md
=> document array of objects, closes #177

content/nav.md
Here's a nav update, this is what it looks like:
=> first pass at organizing nav, loosely based on mkeys suggestions

content/docs/operators.md
Changes spaces to a tab in the first `prop` since otherwise it wasn't coherent and broke the case.
Inverted "local" and "global" for `tag`.
=> small fixes to operators documentation: prop, tag
